/* Generated By:JJTree: Do not edit this line. ASTARRAYSIZE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARRAYSIZE extends SimpleNode {
  public ASTARRAYSIZE(int id) {
    super(id);
  }

  public ASTARRAYSIZE(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7aa7d7ca8f3cf9d8e4cbf84b1bbee9f (do not edit this line) */
