/* Generated By:JJTree: Do not edit this line. ASTARRAYACCESS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARRAYACCESS extends SimpleNode {
  public ASTARRAYACCESS(int id) {
    super(id);
  }

  public ASTARRAYACCESS(YalParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6574219720363313732db25bd18012bc (do not edit this line) */
