/* Generated By:JJTree: Do not edit this line. ASTCALL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCALL extends SimpleNode {
  public ASTCALL(int id) {
    super(id);
  }

  public ASTCALL(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2918fe612d5f50080347e885c3c41883 (do not edit this line) */
