/* Generated By:JJTree: Do not edit this line. ASTDECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTDECLARATION extends SimpleNode {

	public String operator = "";
	public Integer integer = null;

	public ASTDECLARATION(int id) {
		super(id);
	}

	public ASTDECLARATION(Exemplo p, int id) {
		super(p, id);
	}

	public void dump(String prefix) {
		if(this.integer == null)
			return;
		
		System.out.println(toString(prefix));
		if (children == null) {
			System.out.println(prefix + "\"" + this.operator + this.integer + "\"");
		}
		if (children != null) {
			System.out.println(prefix + "\"" + this.operator + this.integer + "\"");
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode) children[i];
				if (n != null) {
					n.dump(prefix + " ");
				}
			}
		}
	}
}
/*
 * JavaCC - OriginalChecksum=15e484f6685479de829a265fe7dc2264 (do not edit this
 * line)
 */
