/* Generated By:JJTree: Do not edit this line. ASTEXPRTEST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEXPRTEST extends SimpleNode {
  public ASTEXPRTEST(int id) {
    super(id);
  }

  public ASTEXPRTEST(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84ace95a14ce1b83690e2ed7d5fb8266 (do not edit this line) */
