/* Generated By:JJTree: Do not edit this line. ASTINDEX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTINDEX extends SimpleNode {
  public ASTINDEX(int id) {
    super(id);
  }

  public ASTINDEX(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6cdf649ac9dfd5482db2faae8227a9d6 (do not edit this line) */
