/* Generated By:JJTree: Do not edit this line. ASTIF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIF extends SimpleNode {
  public ASTIF(int id) {
    super(id);
  }

  public ASTIF(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70186ec23c5467e3d3fb2d0c083333b1 (do not edit this line) */
