/* Generated By:JJTree: Do not edit this line. ASTRHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRHS extends SimpleNode {
  public ASTRHS(int id) {
    super(id);
  }

  public ASTRHS(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23931e4bde4415406c7ace06dd9f3616 (do not edit this line) */
