/* Generated By:JJTree: Do not edit this line. ASTSCALARELEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSCALARELEMENT extends SimpleNode {
  public ASTSCALARELEMENT(int id) {
    super(id);
  }

  public ASTSCALARELEMENT(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=017d76a99776255e9399c9811b98ec18 (do not edit this line) */
