/* Generated By:JJTree: Do not edit this line. ASTSCALARACCESS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSCALARACCESS extends SimpleNode {
  public ASTSCALARACCESS(int id) {
    super(id);
  }

  public ASTSCALARACCESS(Exemplo p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2099131e4dba80ed3ef7b4991df83627 (do not edit this line) */
