/* Generated By:JavaCC: Do not edit this line. ExemploTreeConstants.java Version 5.0 */
public interface ExemploTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVOID = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTRHS = 6;
  public int JJTARRAYSIZE = 7;
  public int JJTTERM = 8;
  public int JJTEXPRTEST = 9;
  public int JJTWHILE = 10;
  public int JJTIF = 11;
  public int JJTCALL = 12;
  public int JJTARGUMENT = 13;
  public int JJTARRAYACCESS = 14;
  public int JJTSCALARACCESS = 15;
  public int JJTINDEX = 16;


  public String[] jjtNodeName = {
    "MODULE",
    "DECLARATION",
    "FUNCTION",
    "void",
    "ARRAYELEMENT",
    "SCALARELEMENT",
    "RHS",
    "ARRAYSIZE",
    "TERM",
    "EXPRTEST",
    "WHILE",
    "IF",
    "CALL",
    "ARGUMENT",
    "ARRAYACCESS",
    "SCALARACCESS",
    "INDEX",
  };
}
/* JavaCC - OriginalChecksum=ff0bbd77430d8c2a4cb349f9ec48a7fa (do not edit this line) */
