/* Generated By:JavaCC: Do not edit this line. ExemploTreeConstants.java Version 5.0 */
public interface ExemploTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTVOID = 6;
  public int JJTSTMT = 7;
  public int JJTASSIGN = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTWHILE = 13;
  public int JJTID = 14;
  public int JJTCALL = 15;
  public int JJTARGUMENTLIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTARRAYACCESS = 18;
  public int JJTSCALARACCESS = 19;
  public int JJTINDEX = 20;


  public String[] jjtNodeName = {
    "MODULE",
    "DECLARATION",
    "FUNCTION",
    "VARLIST",
    "ARRAYELEMENT",
    "SCALARELEMENT",
    "void",
    "STMT",
    "ASSIGN",
    "RHS",
    "ARRAYSIZE",
    "TERM",
    "EXPRTEST",
    "WHILE",
    "ID",
    "CALL",
    "ARGUMENTLIST",
    "ARGUMENT",
    "ARRAYACCESS",
    "SCALARACCESS",
    "INDEX",
  };
}
/* JavaCC - OriginalChecksum=1ec9fdf320fbee9f6718860a553ac2d5 (do not edit this line) */
