/* Generated By:JJTree: Do not edit this line. ASTASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTASSIGN extends SimpleNode
{

	public ASTASSIGN(int id)
	{
		super(id);
	}

	public ASTASSIGN(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=175424ad9486a7061d0c8f2ff92746cc (do not edit this
 * line)
 */
