/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public
class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(YalParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5727e8720d0baa68f21f3cd982741283 (do not edit this line) */
