/* Generated By:JJTree: Do not edit this line. ASTIF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTIF extends SimpleNode
{

	public ASTIF(int id)
	{
		super(id);
	}

	public ASTIF(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=d977164d10bad5160af8823f99c22064 (do not edit this
 * line)
 */
