/* Generated By:JJTree: Do not edit this line. ASTLHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTLHS extends SimpleNode
{

	public ASTLHS(int id)
	{
		super(id);
	}

	public ASTLHS(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=d6409fd9f01a3b0c89590361470ac4ff (do not edit this
 * line)
 */
