/* Generated By:JJTree: Do not edit this line. ASTSTATEMENTS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTSTATEMENTS extends SimpleNode
{

	public ASTSTATEMENTS(int id)
	{
		super(id);
	}

	public ASTSTATEMENTS(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=1a0c164473e240a3a7e435e620b5b121 (do not edit this
 * line)
 */
