/* Generated By:JJTree: Do not edit this line. ASTVARS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTVARS extends SimpleNode
{

	public ASTVARS(int id)
	{
		super(id);
	}

	public ASTVARS(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=4b1aa1cada2b39e29306bf4d34ac56cf (do not edit this
 * line)
 */
