/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal2jvm.ast;

public class ASTWHILE extends SimpleNode
{

	public ASTWHILE(int id)
	{
		super(id);
	}

	public ASTWHILE(YalParser p, int id)
	{
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=f3197642a13c192c5bb27c94208882af (do not edit this
 * line)
 */
