/* Generated By:JavaCC: Do not edit this line. YalParserTreeConstants.java Version 5.0 */
package yal2jvm.ast;

public interface YalParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTARGUMENTS = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTSTATEMENTS = 6;
  public int JJTVOID = 7;
  public int JJTCALL = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTWHILE = 13;
  public int JJTIF = 14;
  public int JJTELSE = 15;
  public int JJTARGUMENT = 16;
  public int JJTARRAYACCESS = 17;
  public int JJTSCALARACCESS = 18;
  public int JJTINDEX = 19;


  public String[] jjtNodeName = {
    "MODULE",
    "DECLARATION",
    "FUNCTION",
    "ARGUMENTS",
    "ARRAYELEMENT",
    "SCALARELEMENT",
    "STATEMENTS",
    "void",
    "CALL",
    "RHS",
    "ARRAYSIZE",
    "TERM",
    "EXPRTEST",
    "WHILE",
    "IF",
    "ELSE",
    "ARGUMENT",
    "ARRAYACCESS",
    "SCALARACCESS",
    "INDEX",
  };
}
/* JavaCC - OriginalChecksum=d25106826bc536daa80fb222b39270a8 (do not edit this line) */
