/* Generated By:JavaCC: Do not edit this line. YalParserTreeConstants.java Version 5.0 */
package yal2jvm.ast;

public interface YalParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTARGUMENTS = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTSTATEMENTS = 6;
  public int JJTVOID = 7;
  public int JJTCALL = 8;
  public int JJTASSIGN = 9;
  public int JJTLHS = 10;
  public int JJTRHS = 11;
  public int JJTARRAYSIZE = 12;
  public int JJTTERM = 13;
  public int JJTEXPRTEST = 14;
  public int JJTWHILE = 15;
  public int JJTIF = 16;
  public int JJTELSE = 17;
  public int JJTARGUMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "MODULE",
    "DECLARATION",
    "FUNCTION",
    "ARGUMENTS",
    "ARRAYELEMENT",
    "SCALARELEMENT",
    "STATEMENTS",
    "void",
    "CALL",
    "ASSIGN",
    "LHS",
    "RHS",
    "ARRAYSIZE",
    "TERM",
    "EXPRTEST",
    "WHILE",
    "IF",
    "ELSE",
    "ARGUMENT",
    "ARRAYACCESS",
    "SCALARACCESS",
    "INDEX",
  };
}
/* JavaCC - OriginalChecksum=a8c9edf50e5bb3a5152a7b50161d467f (do not edit this line) */
