/* Generated By:JJTree: Do not edit this line. ASTARGUMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTARGUMENT extends SimpleNode {
  public ASTARGUMENT(int id) {
    super(id);
  }

  public ASTARGUMENT(YalParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8487cc95adcac2e8e9f0ee712d2eb9c5 (do not edit this line) */
