/* Generated By:JJTree: Do not edit this line. ASTTERM.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTERM extends SimpleNode {
  public ASTTERM(int id) {
    super(id);
  }

  public ASTTERM(YalParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3c6e82ee5fb454b3142fb846a70184e (do not edit this line) */
