/* Generated By:JavaCC: Do not edit this line. YalParserTreeConstants.java Version 5.0 */
public interface YalParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVOID = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTRHS = 6;
  public int JJTARRAYSIZE = 7;
  public int JJTTERM = 8;
  public int JJTEXPRTEST = 9;
  public int JJTWHILE = 10;
  public int JJTIF = 11;
  public int JJTCALL = 12;
  public int JJTARGUMENT = 13;
  public int JJTARRAYACCESS = 14;
  public int JJTSCALARACCESS = 15;
  public int JJTINDEX = 16;


  public String[] jjtNodeName = {
    "MODULE",
    "DECLARATION",
    "FUNCTION",
    "void",
    "ARRAYELEMENT",
    "SCALARELEMENT",
    "RHS",
    "ARRAYSIZE",
    "TERM",
    "EXPRTEST",
    "WHILE",
    "IF",
    "CALL",
    "ARGUMENT",
    "ARRAYACCESS",
    "SCALARACCESS",
    "INDEX",
  };
}
/* JavaCC - OriginalChecksum=5e74e9e3f21b3f173575da748df9ef6f (do not edit this line) */
